# Machine Learning LAB , Autumn 2018  

### arif-cse@metoruni.edu.bd

## NumPy
 

### Arrays 

In [1]:
#import numpy 
import numpy as  np 
# we certainly should not do the following:
# from numpy import *

# check version
print 'Numpy version ='+np.version.full_version
print '\n'

# numpy Array 
A = np.array([0,1,2,3,4,5])
print 'A =', A
print 'A.shape=', A.shape , type(A)
print 'A.ndim=', A.ndim
print '\n'

B = A.reshape((3,2))
print 'B =',  B 
print 'B.shape=', B.shape, type(B)
print 'B.ndim=', B.ndim


Numpy version =1.13.3


A = [0 1 2 3 4 5]
A.shape= (6,) <type 'numpy.ndarray'>
A.ndim= 1


B = [[0 1]
 [2 3]
 [4 5]]
B.shape= (3, 2) <type 'numpy.ndarray'>
B.ndim= 2


In [2]:
# Create a 4x4 array of all zeros
array1 = np.zeros((4,4))
print 'array1=','\n',array1
print 


array1= 
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]



In [3]:
# Create a 4x4 array of all ones
array2 = np.ones((4,4))
print 'array2=','\n', array2
print 

array2= 
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]



In [4]:
# Create a 4x4 constant array
array3 = np.full((4,4), 5)
print 'array3=\n', array3
print 


array3=
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]



In [5]:
# Create a 4x4 array filled with random values
array4 = np.random.random((4,4))
print 'array4=','\n',array4
print 

array4= 
[[ 0.13271625  0.49300019  0.79321644  0.29777175]
 [ 0.90681354  0.67406747  0.03596549  0.4819682 ]
 [ 0.39391679  0.57860466  0.74701169  0.61635215]
 [ 0.0433275   0.73072886  0.88185018  0.27811524]]



In [6]:
# Create a 4x4 identity matrix
e = np.eye(4)
print 'Identity matrix, e=', '\n',e

Identity matrix, e= 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [7]:
# convert list to array
f = np.array([2, 3, 1, 0])
print f


[2 3 1 0]


In [8]:
# arange() will create arrays with regularly incrementing values
g = np.arange(20)
print g


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
# note mix of tuple and lists
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print h

[[ 0.+0.j  1.+0.j  2.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 1.+1.j  3.+0.j  2.+0.j]]


In [10]:
# create an array of range with float data type
i = np.arange(1, 8, dtype=np.float)
print i

[ 1.  2.  3.  4.  5.  6.  7.]


In [11]:
# linspace() will create arrays with a specified number of items which are
# spaced equally between the specified beginning and end values
j = np.linspace(2., 4., 5)
print j

[ 2.   2.5  3.   3.5  4. ]


In [12]:
# indices() will create a set of arrays stacked as a one-higher dimensioned array, 
#one per dimension with each representing variation in that dimension
k = np.indices((2,2))
print k

[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]


### Data Types

In [13]:
# Let numpy choose the datatype
x = np.array([0, 1])
y = np.array([2.0, 3.0])
# Force a particular datatype
z = np.array([5, 6], dtype=np.int64)
print x.dtype, y.dtype, z.dtype

int32 float64 int64


## Array Indexing 
### Field Access

In [14]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print "x['a'].shape: ",x['a'].shape
print "x['a'].dtype: ", x['a'].dtype
print "x['b'].shape: ", x['b'].shape
print "x['b'].dtype: ", x['b'].dtype

x['a'].shape:  (3, 3)
x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64


### Basic Slicing

In [15]:
x = np.array([5, 6, 7, 8, 9])
x[1:7:2]

print x[-2:5]
print x[-1:1:-1]
x[4:]

[8 9]
[9 8 7]


array([9])

In [16]:
y = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print "Shape of y: ", x.shape
y[1:3]

x[...,0]


Shape of y:  (5,)


array(5)

In [17]:
# Create a rank 2 array with shape (3, 4)
a = np.array([[5,6,7,8], [1,2,3,4], [9,10,11,12]])
print "Array a:", a

Array a: [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


In [18]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
# [6 7]]
b = a[:2, 1:3]
print "Array b:", b

Array b: [[6 7]
 [2 3]]


In [19]:
print a[0, 1]
b[0, 0] = 77
print a[0, 1]

6
77


In [20]:
row_r1 = a[1,:]# Rank 1 view of the second row of a
row_r2 = a[1:2,:]# Rank 2 view of the second row of a
print row_r1, row_r1.shape # Prints "[5 6 7 8] (4,)"
print row_r2, row_r2.shape # Prints "[[5 6 7 8]] (1, 4)"

[1 2 3 4] (4,)
[[1 2 3 4]] (1, 4)


In [21]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print col_r1, col_r1.shape # Prints "[ 2 6 10] (3,)"
print col_r2, col_r2.shape

[77  2 10] (3,)
[[77]
 [ 2]
 [10]] (3, 1)
